[package]
name = "energy-calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.0"
eframe = { version = "0.31.0", default-features = false, features = [
  "default_fonts",
  "glow"
] }
log = "0.4.25"
env_logger = "0.11.6"
